# Generated by Django 4.2.1 on 2023-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habitname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='stdtext',
            field=models.CharField(max_length=200),
        ),
    ]
